package csye.Assignment.student_info_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Announcements")
public class Announcement extends BasicDynamoObject {

	private long id;
	private long announcementId;
	private String announcementText;
	private long boardId;
	
	public Announcement() {
		
	}
	
	public Announcement(long announcementId, String announcementText, long boardId) {
		this.announcementId = announcementId;
		this.announcementText = announcementText;
		this.boardId = boardId;
	}
	

	@Override
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public long getId() {
		return this.id;
	}

	@Override
	public void setId(long id) {
		this.id = id;
	}
 
	@DynamoDBIndexRangeKey(attributeName="AnnouncementId", globalSecondaryIndexName = "AnnouncementId")
	public long getAnnouncementId() {
		return announcementId;
	}
	
	public void setAnnouncementId(long announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName="AnnouncementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBIndexHashKey(attributeName="BoardId", globalSecondaryIndexName = "BoardIdInAnnouncement")
	public long getBoardId() {
		return boardId;
	}

	public void setBoardId(long boardId) {
		this.boardId = boardId;
	}
	
	
	
}