package csye.Assignment.student_info_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Announcements")
public class Announcement extends BasicDynamoObject {

	private String id;
	private String announcementId;
	private String announcementText;
	private String boardId;
	private String courseId;
	
	public Announcement() {
		
	}
	
	public Announcement(String announcementId, String announcementText, String boardId, String courseId) {
		this.announcementId = announcementId;
		this.announcementText = announcementText;
		this.boardId = boardId;
		this.courseId = courseId;
	}
	

	@Override
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return this.id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}
 
	@DynamoDBIndexRangeKey(attributeName="AnnouncementId", globalSecondaryIndexName = "Board-Announcement-Index")
	public String getAnnouncementId() {
		return announcementId;
	}
	
	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName="AnnouncementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBIndexHashKey(attributeName="BoardId", globalSecondaryIndexName = "Board-Announcement-Index")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName="CourseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	
}