package csye.Assignment.student_info_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Boards")
public class Board extends BasicDynamoObject {

	private String id;
	private Long courseId;
	
	public Board() {
		
	}
	
	public Board(Long courseId) {
		this.courseId = courseId;
	}
	
	@Override
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="CourseId") 
	@DynamoDBIndexHashKey(attributeName="CourseId", globalSecondaryIndexName = "CourseIdInBorad")
	public Long getCourseId() {
		return courseId;
	}

	public void setCourseId(Long courseId) {
		this.courseId = courseId;
	}
	
	
	
}