package csye.Assignment.student_info_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Boards")
public class Board extends BasicDynamoObject {

	private long id;
	private long courseId;
	
	public Board() {
		
	}
	
	public Board(long courseId) {
		this.courseId = courseId;
	}
	
	public Board(long id, long courseId) {
		this.id = id;
		this.courseId = courseId;
	}
	
	
	@Override
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public long getId() {
		return id;
	}

	@Override
	public void setId(long id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="CourseId") 
	@DynamoDBIndexHashKey(attributeName="CourseId", globalSecondaryIndexName = "CourseIdInBorad")
	public long getCourseId() {
		return courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}
	
	
	
}