package csye.Assignment.student_info_system.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Courses")
public class Course extends BasicDynamoObject {
	private String id;
	private String courseId;
	private String professorId;
	private String taId;
	private String department;
	
	private String boardId;
	private List<String> roster;
	private String notificationTopic;

	public Course() {
		
	}
	
	public Course(String courseId, String professorId, String taId, String department) {
		this.courseId = courseId;
		this.professorId = professorId;
		this.taId = taId;
		this.department = department;
		this.roster = new ArrayList<>();
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="CourseId") 
	@DynamoDBIndexHashKey(attributeName="CourseId", globalSecondaryIndexName = "CourseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBAttribute(attributeName="ProfessorId")
	public String getProfessorId() {
		return professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName="TAId")
	public String getTAId() {
		return taId;
	}

	public void setTAId(String taId) {
		this.taId = taId;
	}
	
	@DynamoDBAttribute(attributeName="Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="BoardId")
	public String getBoard() {
		return boardId;
	}

	public void setBoard(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName="Roster")
	public List<String> getRoster() {
		return roster;
	}

	public void setRoster(List<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName="Topic")
	public String getNotificationTopic() {
		return notificationTopic;
	}

	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}
	
	
}
