package csye.Assignment.student_info_system.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;

public class Course extends BasicDynamoObject {
	private long id;
	private long courseId;
	private long professorId;
	private long TAId;
	private String department;
	private long boardId;
	private List<Long> roster;

	public Course() {
		
	}
	
	public Course(long courseId, long professorId, long TAId, String department, long boardId, List<Long> roster) {
		this.courseId = courseId;
		this.professorId = professorId;
		this.TAId = TAId;
		this.department = department;
		this.boardId = boardId;
		this.roster = roster;
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="CourseId") 
	@DynamoDBIndexHashKey(attributeName="CourseId", globalSecondaryIndexName = "CourseIdInCourse")
	public long getCourseId() {
		return courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBAttribute(attributeName="ProfessorId")
	public long getProfessorId() {
		return professorId;
	}

	public void setProfessorId(long professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName="TAId")
	public long getTAId() {
		return TAId;
	}

	public void setTAId(long tAId) {
		TAId = tAId;
	}
	
	@DynamoDBAttribute(attributeName="Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="BoardId")
	public long getBoard() {
		return boardId;
	}

	public void setBoard(long boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName="Roster")
	public List<Long> getRoster() {
		return roster;
	}

	public void setRoster(List<Long> roster) {
		this.roster = roster;
	}

	
}
