package csye.Assignment.student_info_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Professors")
public class Professor extends BasicDynamoObject {
	private String id;
	private Long professorId;
	private String firstName;
	private String lastName;
	private String joinDate;
	private String department;
	
	
	public Professor() {
		
	}
	
	public Professor(Long professorId, String firstName, String lastName, String joinDate, String department) {
		this.professorId = professorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.joinDate = joinDate;
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName="ProfessorId") 
	@DynamoDBIndexHashKey(attributeName="ProfessorId", globalSecondaryIndexName = "ProfessorId")
	public Long getProfessorId() {
		return professorId;
	}

	public void setProfessorId(Long professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "ProfessorFirstName")
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName = "ProfessorLastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute(attributeName = "ProfessorJoinDate")
	public String getJoinDate() {
		return joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
