package csye.Assignment.student_info_system.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Students")
public class Student extends BasicDynamoObject {
	private String id;
	private String studentId;
	private String firstName;
	private String lastName;
	private String joinDate;
	private String department;
	private List<String> enrolledClass;
	private String email;
	
	public Student() {
		
	}
	
	public Student(String firstName, String lastName, String studentId, String joinDate, String department, List<String> enrolledClass, String email) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.studentId = studentId;
		this.joinDate = joinDate;
		this.department = department;
		this.enrolledClass = enrolledClass;
		this.email = email;
	}
	
	@DynamoDBAttribute(attributeName = "StudentFirstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName = "StudentLastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "StudentJoinDate")
	public String getJoinDate() {
		return joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "EnrolledClasses")
	public List<String> getEnrolledClass() {
		return enrolledClass;
	}
	
	public void setEnrolledClass(List<String> enrolledClass) {
		this.enrolledClass = enrolledClass;
	}
	
	@DynamoDBIndexHashKey(attributeName="StudentId", globalSecondaryIndexName = "StudentId")
	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	
	@DynamoDBAttribute(attributeName = "Email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	
}
