package csye.Assignment.student_info_system.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Students")
public class Student extends BasicDynamoObject {
	private long id;
	private long studentId;
	private String firstName;
	private String lastName;
	private String joinDate;
	private String department;
	private List<Long> enrolledClass;
	
	public Student() {
		
	}
	
	public Student(String firstName, String lastName, long studentId, String joinDate, String department, List<Long> enrolledClass) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.studentId = studentId;
		this.joinDate = joinDate;
		this.department = department;
		this.enrolledClass = enrolledClass;
	}
	
	@DynamoDBAttribute(attributeName = "StudentFirstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName = "StudentLastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "StudentJoinDate")
	public String getJoinDate() {
		return joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "EnrolledCourses")
	public List<Long> getEnrolledClass() {
		return enrolledClass;
	}
	
	public void setEnrolledClass(List<Long> enrolledClass) {
		this.enrolledClass = enrolledClass;
	}

	@DynamoDBAttribute(attributeName="StudentId") 
	@DynamoDBIndexHashKey(attributeName="StudentId", globalSecondaryIndexName = "StudentId")
	public long getStudentId() {
		return studentId;
	}


	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}
}
